runtime: nodejs18

service: frontend

handlers:
  - url: /.*
    static_files: dist/stock-tracker/index.html
    upload: dist/stock-tracker/index.html
    secure: always
    redirect_http_response_code: 301

  - url: /(.*)
    static_files: dist/stock-tracker/\1
    upload: dist/stock-tracker/(.*)
    secure: always
    redirect_http_response_code: 301

automatic_scaling:
  min_instances: 0
  max_instances: 5
